services:
  - type: web
    name: love_project
    env: python
    plan: free
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn love_project.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "love-project-8ihk.onrender.com,localhost,127.0.0.1"
